development:
  dialect: postgres
  datasource: host=localhost dbname=postgres user=postgres password=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
  dir: db/migrations

# production:
#   dialect: postgres
#   datasource: dbname=myapp sslmode=disable
#   dir: migrations/postgres
#   table: migrations
